# Site settings
title: "Om Num Num Num. Me Love to Eat Data."
email: 
#description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://quantmonster.github.io"
#twitter_username: karpathy
#github_username:  karpathy

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: minima

minima:
  skin: dark